//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administrator()
        {
            this.Comics = new HashSet<Comic>();
            this.Follows = new HashSet<Follow>();
        }
    
        public int UserID { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên đăng nhập!")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập mật khẩu!")]
        public string Passwords { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập họ tên!")]
        public string Fullname { get; set; }
        
        [Required(ErrorMessage = "Bạn chưa nhập Email!")]
        [EmailAddress(ErrorMessage = "Email định dạng không đúng")]
        public string Email { get; set; }
        public string Avatar { get; set; }

        [Required(ErrorMessage = "User có được cấp quyền Admin không ('1' có) và ('0' không)")]
        public Nullable<int> isAdmin { get; set; }

        [Required(ErrorMessage = "User có được hoạt động không ('1' có) và ('0' không)")]
        public Nullable<int> Allowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comic> Comics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
    }
}
