//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Comic
    {
        public int ComicID { get; set; }
        public string CategoryID { get; set; }
        public string Descriptions { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Comic Comic { get; set; }
    }
}
