//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Comic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comic()
        {
            this.Category_Comic = new HashSet<Category_Comic>();
            this.Follows = new HashSet<Follow>();
            this.TopNames = new HashSet<TopName>();
        }
    
        public int ComicID { get; set; }

        [Required(ErrorMessage = "Bạn chưa nhập tên chuyện!")]
        public string Comicname { get; set; }
        public string Picture { get; set; }

        [Required(ErrorMessage = "nhập tên tác giả hoặc để 'Đang Cập Nhật'!")]
        public string Author { get; set; }

        [Required(ErrorMessage = "mô tả chuyện!")]
        public string Brief { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Tags { get; set; }
        public Nullable<int> ViewNo { get; set; }
        public string Statuss { get; set; }
        public int UserID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_Comic> Category_Comic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopName> TopNames { get; set; }
    }
}
