//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWeb.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComicWebEntities : DbContext
    {
        public ComicWebEntities()
            : base("name=ComicWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Comic> Category_Comic { get; set; }
        public virtual DbSet<Comic> Comics { get; set; }
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<TopComic> TopComics { get; set; }
        public virtual DbSet<TopName> TopNames { get; set; }
    }
}
