//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWeb.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int UserID { get; set; }
        public int ComicID { get; set; }
        public string Descriptions { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Comic Comic { get; set; }
    }
}
